# Generated by Django 4.0.2 on 2022-02-24 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(help_text='Enter your comment...')),
                ('author', models.ForeignKey(default='Deleted user', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('pet_name', models.CharField(default='Unnamed pet', max_length=64)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(help_text='Describe your problem to us :)')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'Assigned'), (2, 'In Progress'), (3, 'Resolved'), (4, 'Closed')])),
                ('is_public', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('pet_specialist', models.ForeignKey(default='Deleted user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='assigned_%(class)ss', related_query_name='assigned_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
