# Generated by Django 4.0.2 on 2022-02-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doghelp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
