# Generated by Django 4.0.2 on 2022-03-04 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doghelp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='video',
            field=models.ForeignKey(default='This video has been deleted.', on_delete=django.db.models.deletion.SET_NULL, null=True, to='doghelp.video'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'Assigned'), (2, 'In Progress'), (3, 'Resolved'), (4, 'Closed')], default=0),
        ),
    ]
