# Generated by Django 4.0.2 on 2022-03-04 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doghelp', '0002_case_video_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doghelp.video'),
        ),
    ]
