# Generated by Django 4.0.2 on 2022-03-04 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doghelp', '0003_alter_case_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='pet_specialist',
            field=models.ForeignKey(default='Unknown user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='assigned_%(class)ss', related_query_name='assigned_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default='Unknown user', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
