# Generated by Django 4.0.2 on 2022-03-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doghelp', '0004_alter_case_pet_specialist_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to='videos/', verbose_name=''),
        ),
    ]
