# Generated by Django 4.0.2 on 2022-03-07 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doghelp', '0005_alter_video_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doghelp.video'),
        ),
    ]
