# Generated by Django 4.0.2 on 2022-03-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doghelp', '0007_alter_case_pet_specialist_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='doghelp.video'),
        ),
    ]
